### ISSUE TITLE
How to enable the demangler

### ISSUE THREAD

**Issue by JayFoxRox** [Cuyler36/CodeWarriorDemangler#3]
Microsoft and GNU demanglers have:

- https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/MicrosoftDemangler/src/main/java/ghidra/app/plugin/core/analysis/MicrosoftDemanglerAnalyzer.java
- https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/GnuDemangler/src/main/java/ghidra/app/plugin/core/analysis/GnuDemanglerAnalyzer.java respectively

So the existing demanglers have a GUI entry for "Demangler Microsoft" and "Demangler GNU"  in the one-shot analysis, and the auto-analysis options.

However, this extension doesn't seem to have anything like this yet, so I'm not sure how to trigger it.
The only way it seems to be triggered is in https://github.com/Cuyler36/Ghidra-GameCube-Loader/blob/52573c9ff6207f5bde733ae0303d69dcb6bb6fbe/src/main/java/gamecubeloader/common/SymbolLoader.java#L445-L452 (through code, not user request).
However, I'm not using `gamecubeloader`, but my executables symbols are still mangled in CodeWarrior style.

---

Even if a GUI was added, I assume that it wouldn't report as being able to demangle, because of:

https://github.com/Cuyler36/CodeWarriorDemangler/blob/3eb81b5450e2de1e7b5272a56b0925c3025d9748/src/main/java/cwdemangler/CodeWarriorDemangler.java#L20
https://github.com/Cuyler36/CodeWarriorDemangler/blob/3eb81b5450e2de1e7b5272a56b0925c3025d9748/src/main/java/cwdemangler/CodeWarriorDemangler.java#L442-L450

I assume this means that a property of the name "DemangleCW" must exist for my program.

- How do I ensure the "DemangleCW"-property exists?
- Is there another way to trigger demangling in Ghidra? (potentially ignoring the `canDemangle` check?)
- Asked differently: How do I make this demangler functional?

**Comment by Cuyler36** [comment]
Thanks, this was initially created for use in the GameCube loader plugin as you noted. I created this separate repository by request, so I didn't research much into what was necessary to get it working. The latest commit/[release](https://github.com/Cuyler36/CodeWarriorDemangler/releases/tag/0.1) should fix this.
